services:
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
      - WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower

  express-app:
    image: alxcd/express-app
    container_name: express-app
    ports:
      - 80:80
    labels:
      - "com.centurylinklabs.watchtower.enable=true"